### ISSUE TITLE
Mark delivery as complete workflow

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#11]
I should be assisted with the app in delivering food boxes. The app should allow me to mark a delivery as completed.

**Comment by peterghrong** [comment]
Here, I added a similar workflow in Curtis' file, because we ran out of free files and I suck at Figma

https://www.figma.com/file/cfr3NDIb3gzc9BN3OPUfST/User-workflows?node-id=0%3A1
