### ISSUE TITLE
See all previous tasks workflow

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#12]
I should be assisted with the app in delivering food boxes. The app should allow me to see every previous task I’ve completed, This includes the details as well, such as
- Date and time of delivery
- Number of portions
- Name and address

**Comment by CurtisMIT** [comment]
@kehwhy I drafted the user workflow for this issue (it's on figma). I'm not sure whether this is what you're looking for so feel free to give me feedback.

**Comment by peterghrong** [comment]
I think this is where the workflow is, sorry that I had to rip your file space, but we ran out of free files and I'm a noob :_)

https://www.figma.com/file/cfr3NDIb3gzc9BN3OPUfST/User-workflows?node-id=0%3A1

**Comment by CurtisMIT** [comment]
@peterghrong Just helped you move. You can create a new frame and put your user workflow there.
