### ISSUE TITLE
Filter previous tasks workflow

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#14]
I should be assisted with the app in delivering food boxes. The app should allow me to see every previous delivery I’ve completed and I should also be able to filter by date or with a timeframe.

**Comment by peterghrong** [comment]
1. client selects some sort of completed button
2. request to backend API
3. api filters tasks belonging to the specific user with the boolean field "completed" ticked to true
4. api returns a list of tasks
5. render in client.
