### ISSUE TITLE
authentication workflow - SMS option

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#15]
As a MADA volunteer, I should be able to authenticate myself using the app through a login page. The password should be an authentication code sent via SMS to the user's device.

**Comment by peterghrong** [comment]
I don't think there really exist a free SMS API, Twilio is 0.0075 per text, there are varieties of APIs with free monthly allowance like Amazon SNS (100 SMS per month), but since there is going to be a limit, Idk how achievable this issue really is without some sort of consistant funding.

**Comment by kehwhy** [comment]
fair point, let's table it for now and if it's something MADA would like to invest in we can look at it again in the future.
