### ISSUE TITLE
respond to availability request workflow

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#16]
As a user, I will receive a push notification/SMS asking me if I am available to make deliveries on a given date (ie. November 10th). I should open the app and respond yes, indicating I can receive deliveries on that date, or no, indicating I cannot receive deliveries on that date.

**Comment by mahroo12** [comment]
Link to user workflow: https://drive.google.com/file/d/1W3dnbyGBPrRoKJQUZXZI6TaCJXxGuyC3/view?usp=sharing
