### ISSUE TITLE
Task db model

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#22]
Add the db model for Task

Class diagram: [https://drive.google.com/file/d/13aiD-ivql-npTbgwyLVry0ToKAMEZFpc/view?usp=sharing](https://drive.google.com/file/d/13aiD-ivql-npTbgwyLVry0ToKAMEZFpc/view?usp=sharing)

**Comment by peterghrong** [comment]
Soz didn't see this, I stole the db model part, you can still work on the api

**Comment by peterghrong** [comment]
This is done sowerry. Stole it :_(, bit blind
