### ISSUE TITLE
Meal Delivery db model

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#23]
Add the db model for class Meal Delivery

Class diagram: [https://drive.google.com/file/d/13aiD-ivql-npTbgwyLVry0ToKAMEZFpc/view?usp=sharing](https://drive.google.com/file/d/13aiD-ivql-npTbgwyLVry0ToKAMEZFpc/view?usp=sharing)

**Comment by peterghrong** [comment]
This is done too :_(( im insanely blind, sorry @rens000
