### ISSUE TITLE
Can I have higher privilege of the repo please :P

### ISSUE THREAD

**Issue by peterghrong** [hack4impact-mcgill/MADA#27]
It would be convenient for everyone I think if I merge some dumb sh*t and break everything. e.g the GH action PR. It would also be convenient for deployment, I think you might need to own the repo to deploy something through online services like vercel or heroku. 

x much love :)

**Comment by kehwhy** [comment]
hihi made you an admin :))

**Comment by peterghrong** [comment]
Thank you Katie
