### ISSUE TITLE
Delete api endpoint for task

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#34]
Delete a task with the DELETE endpoint 
An example of the REST endpoints - [https://github.com/hack4impact-mcgill/mu-crm-tool/blob/main/backend/app/project/routes.py](https://github.com/hack4impact-mcgill/mu-crm-tool/blob/main/backend/app/project/routes.py)

More info on REST api endpoints: https://www.restapitutorial.com/lessons/httpmethods.html

**Comment by peterghrong** [comment]
@pengyk  finished this
