### ISSUE TITLE
Update api endpoints for task

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#36]
Update a task with the PUT endpoint 
An example of the REST endpoints - [https://github.com/hack4impact-mcgill/mu-crm-tool/blob/main/backend/app/project/routes.py](https://github.com/hack4impact-mcgill/mu-crm-tool/blob/main/backend/app/project/routes.py)

More info on REST api endpoints: https://www.restapitutorial.com/lessons/httpmethods.html

**Comment by peterghrong** [comment]
Done
