### ISSUE TITLE
Frontend scaffolding - Web

### ISSUE THREAD

**Issue by kehwhy** [hack4impact-mcgill/MADA#42]
Set up an empty react project for the admin web app

**Comment by peterghrong** [comment]
All yours tommy

**Comment by THe142857** [comment]
ah ok thanks

**Comment by peterghrong** [comment]
Quick note
1. Probably use axios for requests
2. Probably use Redux for state management.
3. Please use yarn, npm is annoying,
3. You don't have to install any packages or anything, only if you want to, I think for this step just init a react app is fine.

**Comment by peterghrong** [comment]
Closing, it is done.
